[channel_ids_to_match]
"Gawr Gura Ch. hololive-EN" = "UCoSrY_IQQVpmIRZ9Xf-y93g"
"Watson Amelia Ch. hololive-EN" = "UCyl1z3jo3XHR1riLFKG5UAg"
"Mori Calliope Ch. hololive-EN" = "UCL_qhgtOy0dy1Agp8vkySQg"
"Fauna" = "UCO_aKKYxn4tvrqPjcTzZ6EQ"

[title_filter]
"UCoSrY_IQQVpmIRZ9Xf-y93g" = "(?i).asmr|unarchive|karaoke|unarchived|no archive|WATCH-A-LONG|WATCHALONG|watch-along|birthday|offcollab|off-collab|off collab|SINGING."

[description_filter]
"UCoSrY_IQQVpmIRZ9Xf-y93g" = ".Calliope."

[members_only]
"Gawr Gura Ch. hololive-EN" = "UCoSrY_IQQVpmIRZ9Xf-y93g"

[community_tab]
"Gawr Gura Ch. hololive-EN" = "UCoSrY_IQQVpmIRZ9Xf-y93g"

[webhook]
url = "https://discord.com/api/webhooks/xxxxxxxxxxxxxxxx/yyyyyyyyyyyyyyyyyyyy"

[unarchived_channel_ids_to_match]
"Ninomae Ina'nis Ch. hololive-EN" = "UCMwGHR0BTZuLsmjY_NT5Pwg"

[download_options]
output_path = "%(channel)s/[%(release_date,upload_date)s] %(fulltitle).180B (%(id)s)/[%(release_date,upload_date)s] %(fulltitle).180B [%(channel)s] (%(id)s)"
mux_file = true
download_threads = 4
video_quality = "best"
video_only = false
download_chat = true
thumbnail = true
info_json = true
description = true
video_fetch_method = "yt-dlp"
look_ahead = 48
cookies_file = "/app/cookies.txt"
temp_dir = "/app/temp/"
done_dir = "/app/Done/"
members_dir = "/app/Members"
unarchived_dir = "/app/Done/"
unarchived_tempdir = "/app/temp/unarchived"
remove_ip = true
log_level = "WARNING"
randomise_lists = true
clean_urls = true

[torrent]
enabled = false
options = ["-t", "udp://xxxx/announce", "-c", "Bittorrent"]

[community_tab_options]
archive_file = "/app/com-tab-archive.txt"
community_dir = "/app/CommunityPosts"

